<?php

namespace BVDS\ComptaBundle\Repository;

/**
 * TransCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
